window.Webflow ||= [];
window.Webflow.push(() => {
  // Your JSON data

  const jsonData = {
    schools: [
      {
        Name: 'Aim Academy',
        Slug: 'aim-academy',
        YearStarted: 2021,
        ModelMR: 'stem; culturally-responsive',
        ContactPhone: '612-452-2274',
        Website: 'https://www.aimacademymn.org/',
        Latitude: 44.9507264,
        Longitude: -93.2565603,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Bdote Learning Center',
        Slug: 'bdote-learning-center',
        YearStarted: 2014,
        ModelMR: 'language-immersion',
        ContactPhone: '612-729-9266',
        Website: 'http://bdotelearningcenter.org/',
        Latitude: 44.9503185,
        Longitude: -93.224992,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Beacon Academy',
        Slug: 'beacon-academy',
        YearStarted: 2004,
        ModelMR: 'language-immersion; core-knowledge',
        ContactPhone: '763-546-9999',
        Website: 'http://beaconacademy.com/',
        Latitude: 45.0184866,
        Longitude: -93.3709667,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'BlueSky Charter School',
        Slug: 'bluesky-charter-school',
        YearStarted: 2000,
        ModelMR: 'online',
        ContactPhone: '651-642-0888',
        Website: 'http://www.blueskyschool.org/',
        Latitude: 44.8516397,
        Longitude: -93.2438738,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Cross River Charter School',
        Slug: 'cross-river-charter-school',
        YearStarted: 2021,
        ModelMR: 'oral-language; citizenship',
        ContactPhone: '651-346-0091',
        Website: 'https://crossrivercs.org/',
        Latitude: 44.8410582,
        Longitude: -92.9865294,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Cyber Village Academy',
        Slug: 'cyber-village-academy',
        YearStarted: 1998,
        ModelMR: 'blended; online',
        ContactPhone: '651-523-7170',
        Website: 'http://cybervillageacademy.org/',
        Latitude: 44.902126,
        Longitude: -93.2173308,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'DPSA: North Star Academy',
        Slug: 'dpsa-north-star-academy',
        YearStarted: 1997,
        ModelMR: 'response-to-intervention',
        ContactPhone: '218-728-9556',
        Website: 'http://www.duluthedison.com/',
        Latitude: 46.8275677,
        Longitude: -92.1340559,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'DPSA: Raleigh Academy',
        Slug: 'dpsa-raleigh-academy',
        YearStarted: 1997,
        ModelMR: 'response-to-intervention',
        ContactPhone: '218-628-0697',
        Website: 'http://www.duluthedison.com/',
        Latitude: 46.7315992,
        Longitude: -92.1723163,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'ECHO Charter School',
        Slug: 'echo-charter-school',
        YearStarted: 1997,
        ModelMR: 'core-knowledge; culturally-responsive; project-based-learning',
        ContactPhone: '507-925-4143',
        Website: 'http://www.isd4026.org/',
        Latitude: 44.617944,
        Longitude: -95.4100724,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'EdVisions Off Campus',
        Slug: 'edvisions-off-campus',
        YearStarted: 2005,
        ModelMR: 'online; project-based-learning',
        ContactPhone: '507-248-3101',
        Website: 'http://www.edvisionshighschool.com/',
        Latitude: 44.5282971,
        Longitude: -93.9077438,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Gentry Academy',
        Slug: 'gentry-academy',
        YearStarted: 2021,
        ModelMR: 'leadership; sports-leadership; science-technology',
        ContactPhone: '651-604-8300',
        Website: 'https://gentryacademy.com/',
        Latitude: 45.0498111,
        Longitude: -93.0409191,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'International Spanish Language Academy',
        Slug: 'international-spanish-language-academy',
        YearStarted: 2007,
        ModelMR: 'language-immersion; international-baccalaureate',
        ContactPhone: 'International Baccalaureate',
        Website: 'http://isla-academy.org/',
        Latitude: 44.8960198,
        Longitude: -93.4197104,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Kalon Prep Academy',
        Slug: 'kalon-prep-academy',
        YearStarted: 2021,
        ModelMR: 'strengths-based; whole-child; college-career-focus',
        ContactPhone: '(320) 460-8881',
        Website: 'https://www.kalonprep.org/',
        Latitude: 45.8690046,
        Longitude: -95.3824776,

        Elementary: null,
        Middle: null,
        High: 'High',
      },
      {
        Name: 'Kandiyohi Academy',
        Slug: 'kandiyohi-academy',
        YearStarted: 2022,
        ModelMR: 'stem; culturally-responsive',
        ContactPhone: '612-501-0641',
        Website: 'https://www.kandiyohiacademy.org/',
        Latitude: 45.0754295,
        Longitude: -95.0509212,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Level Up Academy',
        Slug: 'level-up-academy',
        YearStarted: 2015,
        ModelMR: 'science-technology; blended; individualized',
        ContactPhone: '651-408-5559',
        Website: 'https://levelupacademy.org/',
        Latitude: 45.0496059,
        Longitude: -92.9906616,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'Minnesota Excellence in Learning Academy',
        Slug: 'minnesota-excellence-in-learning-academy',
        YearStarted: 2015,
        ModelMR: 'literacy-focused; mtss',
        ContactPhone: '763-205-4396',
        Website: 'http://www.melaschool.org/',
        Latitude: 45.1188019,
        Longitude: -93.4853195,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Minnesota New Country School',
        Slug: 'minnesota-new-country-school',
        YearStarted: 1994,
        ModelMR: 'project-based-learning',
        ContactPhone: '507-248-3353',
        Website: 'https://newcountryschool.com/',
        Latitude: 44.5290276,
        Longitude: -93.9036421,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Modern Montessori',
        Slug: 'modern-montessori',
        YearStarted: 2019,
        ModelMR: 'stem; montessori',
        ContactPhone: '612-440-0681',
        Website: 'https://modernmontessoricharter.org/',
        Latitude: 45.188883,
        Longitude: -93.400315,
        Elementary: 'Prekindergarten-Grade 5',
        Middle: null,
        High: null,
      },
      {
        Name: 'Nasha Shkola',
        Slug: 'nasha-shkola',
        YearStarted: 2012,
        ModelMR: 'language-immersion',
        ContactPhone: '763-496-5550',
        Website: 'http://nashashkolamn.org/',
        Latitude: 45.1083484,
        Longitude: -93.3675084,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'Paladin Career & Technical High School',
        Slug: 'paladin-career-technical-high-school',
        YearStarted: 2003,
        ModelMR: 'project-based-learning; work-based-learning; experiential-learning',
        ContactPhone: '763-786-4799',
        Website: 'http://www.paladincareertech.com/',
        Latitude: 45.1566486,
        Longitude: -93.276384,
        Elementary: null,
        Middle: null,
        High: 'High',
      },
      {
        Name: 'Prodeo Academy',
        Slug: 'prodeo-academy',
        YearStarted: 2013,
        ModelMR: 'literacy-focused',
        ContactPhone: '763-205-9950',
        Website: 'https://prodeoacademy.org',
        Latitude: 45.0439191,
        Longitude: -93.2619188,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'Progeny Academy',
        Slug: 'progeny-academy',
        YearStarted: 2019,
        ModelMR: 'science-technology; social-emotional-learning',
        ContactPhone: '(763) 325-9150',
        Website: 'http://www.progenyacademy.org/',
        Latitude: 45.0632355,
        Longitude: -93.3262265,
        Elementary: null,
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'Sisu Environmental School',
        Slug: 'sisu-environmental-school',
        YearStarted: 2022,
        ModelMR: 'environmental; finnish-model-of-education',
        ContactPhone: '651-890-6988',
        Website: 'http://sisumn.org/',
        Latitude: 44.827278,
        Longitude: -94.497869,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'St. Paul City School',
        Slug: 'st-paul-city-school',
        YearStarted: 2010,
        ModelMR: 'core-knowledge',
        ContactPhone: '651-225-9177',
        Website: 'https://www.stpaulcityschool.org/',
        Latitude: 44.9582633,
        Longitude: -93.1111576,
        Elementary: 'Elementary',
        Middle: 'Middle',
        High: null,
      },
      {
        Name: 'St. Paul School of Northern Lights',
        Slug: 'st-paul-school-of-northern-lights',
        ContactPhone: '651-285-4672',
        YearStarted: null,
        ModelMR: 'inquiry-based; urban-ecosystem',
        Website: 'https://www.schoolofnorthernlights.org/',
        Latitude: 44.9281345,
        Longitude: -93.1278659,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'STEP Academy',
        Slug: 'step-academy',
        YearStarted: 2011,
        Model: 'stem; response-to-intervention; pseo',
        ContactPhone: '651-289-6120',
        Website: 'https://stepacademymn.org/',
        Latitude: 44.9597532,
        Longitude: -93.0651158,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Success Academy',
        Slug: 'success-academy',
        YearStarted: 2016,
        Model: 'stem; science-technology',
        ContactPhone: '612-876-3050',
        Website: 'https://www.successacademymn.org/',
        Latitude: 44.8548095,
        Longitude: -93.2644318,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Terra Nova School',
        Slug: 'terra-nova-school',
        YearStarted: 2015,
        Model: 'project-based-learning; environmental',
        ContactPhone: '952-852-0129',
        Website: 'http://jgesa.org/',
        Latitude: 45.2732761,
        Longitude: -94.0538593,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'The Journey School',
        Slug: 'the-journey-school',
        YearStarted: 2019,
        Model: 'individualized',
        ContactPhone: '(612) 389-1579',
        Website: 'https://www.thejourneyschool.org/',
        Latitude: 44.964411,
        Longitude: -93.1475159,
        Elementary: 'Elementary',
        Middle: null,
        High: null,
      },
      {
        Name: 'Upper Mississippi Academy',
        Slug: 'upper-mississippi-academy',
        YearStarted: 2013,
        Model: 'stem',
        ContactPhone: '651-528-8091',
        Website: 'https://umissacademy.org/',
        Latitude: 44.9495214,
        Longitude: -93.0974287,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Venture Academy',
        Slug: 'venture-academy',
        YearStarted: 2013,
        Model: 'science-technology; pseo; project-based-learning',
        ContactPhone: '612-345-9040',
        Website: 'http://ventureacademies.org/',
        Latitude: 44.9729701,
        Longitude: -93.2185159,
        Elementary: null,
        Middle: 'Middle',
        High: 'High',
      },
      {
        Name: 'Watershed High School',
        Slug: 'watershed-high-school',
        YearStarted: 2021,
        Model: '',
        ContactPhone: '612-452-2274',
        Website: null,
        Latitude: 44.9507264,
        Longitude: -93.2565603,
        Elementary: null,
        Middle: null,
        High: 'High',
      },
    ],
  };

  // Initialize the map
  const map = L.map('map').setView([44.95, -93.12], 12); // Set default center and zoom level

  // Add a tile layer to the map (you can choose other tile providers)
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors',
  }).addTo(map);

  // Iterate over the JSON data and create markers on the map
  jsonData.schools.forEach(function (school) {
    if (school.Latitude && school.Longitude) {
      const marker = L.marker([school.Latitude, school.Longitude]).addTo(map);

      // <p></p>
      // Elementary: ${school.Elementary ? 'Yes' : 'No'}<br>
      // Middle: ${school.Middle ? 'Yes' : 'No'}<br>
      // High: ${school.High ? 'Yes' : 'No'}<br>

      // Create a popup for each marker with school information
      const popupContent = `
      <h6>${school.Name}</h6><br>
      Focus: ${school.Model}<br>
      ${
        school.Website ? `<a href="${school.Website}" target="_blank">${school.Website}</a>` : 'N/A'
      }<br>
      Phone: ${school.ContactPhone}<br>

      <p></p>
      <div style="display: flex; justify-content: end;">
     <div class="button" class = "is-small">
      ${
        school.Slug
          ? `<a href="/schools/${school.Slug}"style="text-decoration: none; color: inherit;">Learn More</a>`
          : 'N/A'
      }<br>
      </div></div>
    `;
      marker.bindPopup(popupContent);
    }
  });
});
